# Generated by Django 6.0.7 on 2026-07-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='todo',
            field=models.CharField(default='Rest day', max_length=100),
        ),
    ]
