# Generated by Django 6.0.7 on 2026-07-26 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_day_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='tday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='main.day'),
        ),
    ]
