# Generated by Django 6.0.7 on 2026-07-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_workout_done_alter_workout_tday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
